/**
 * Election
 * KSF Media's election service
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Election) {
      root.Election = {};
    }
    root.Election.AreaIdentifier = factory(root.Election.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The AreaIdentifier model module.
   * @module model/AreaIdentifier
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>AreaIdentifier</code>.
   * @alias module:model/AreaIdentifier
   * @class
   * @param unAreaIdentifier {String} 
   */
  var exports = function(unAreaIdentifier) {
    var _this = this;

    _this['unAreaIdentifier'] = unAreaIdentifier;
  };

  /**
   * Constructs a <code>AreaIdentifier</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AreaIdentifier} obj Optional instance to populate.
   * @return {module:model/AreaIdentifier} The populated <code>AreaIdentifier</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('unAreaIdentifier')) {
        obj['unAreaIdentifier'] = ApiClient.convertToType(data['unAreaIdentifier'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} unAreaIdentifier
   */
  exports.prototype['unAreaIdentifier'] = undefined;



  return exports;
}));


