/**
 * Election
 * KSF Media's election service
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AreaIdentifier', 'model/AreaInfo'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AreaIdentifier'), require('./AreaInfo'));
  } else {
    // Browser globals (root is window)
    if (!root.Election) {
      root.Election = {};
    }
    root.Election.Area = factory(root.Election.ApiClient, root.Election.AreaIdentifier, root.Election.AreaInfo);
  }
}(this, function(ApiClient, AreaIdentifier, AreaInfo) {
  'use strict';



  /**
   * The Area model module.
   * @module model/Area
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Area</code>.
   * @alias module:model/Area
   * @class
   * @param info {module:model/AreaInfo} 
   */
  var exports = function(info) {
    var _this = this;

    _this['info'] = info;
  };

  /**
   * Constructs a <code>Area</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Area} obj Optional instance to populate.
   * @return {module:model/Area} The populated <code>Area</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('parent')) {
        obj['parent'] = AreaIdentifier.constructFromObject(data['parent']);
      }
      if (data.hasOwnProperty('info')) {
        obj['info'] = AreaInfo.constructFromObject(data['info']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/AreaIdentifier} parent
   */
  exports.prototype['parent'] = undefined;
  /**
   * @member {module:model/AreaInfo} info
   */
  exports.prototype['info'] = undefined;



  return exports;
}));


