/**
 * Election
 * KSF Media's election service
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CandidateMembership', 'model/Gender', 'model/I18N', 'model/Language', 'model/Name', 'model/Status', 'model/Votes'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CandidateMembership'), require('./Gender'), require('./I18N'), require('./Language'), require('./Name'), require('./Status'), require('./Votes'));
  } else {
    // Browser globals (root is window)
    if (!root.Election) {
      root.Election = {};
    }
    root.Election.Candidate = factory(root.Election.ApiClient, root.Election.CandidateMembership, root.Election.Gender, root.Election.I18N, root.Election.Language, root.Election.Name, root.Election.Status, root.Election.Votes);
  }
}(this, function(ApiClient, CandidateMembership, Gender, I18N, Language, Name, Status, Votes) {
  'use strict';



  /**
   * The Candidate model module.
   * @module model/Candidate
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Candidate</code>.
   * @alias module:model/Candidate
   * @class
   * @param candidateNumber {Number} 
   */
  var exports = function(candidateNumber) {
    var _this = this;

    _this['candidateNumber'] = candidateNumber;
  };

  /**
   * Constructs a <code>Candidate</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Candidate} obj Optional instance to populate.
   * @return {module:model/Candidate} The populated <code>Candidate</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('status')) {
        obj['status'] = Status.constructFromObject(data['status']);
      }
      if (data.hasOwnProperty('membership')) {
        obj['membership'] = CandidateMembership.constructFromObject(data['membership']);
      }
      if (data.hasOwnProperty('lastName')) {
        obj['lastName'] = Name.constructFromObject(data['lastName']);
      }
      if (data.hasOwnProperty('age')) {
        obj['age'] = ApiClient.convertToType(data['age'], 'Number');
      }
      if (data.hasOwnProperty('comparativeIndex')) {
        obj['comparativeIndex'] = ApiClient.convertToType(data['comparativeIndex'], 'Number');
      }
      if (data.hasOwnProperty('votes')) {
        obj['votes'] = Votes.constructFromObject(data['votes']);
      }
      if (data.hasOwnProperty('candidateNumber')) {
        obj['candidateNumber'] = ApiClient.convertToType(data['candidateNumber'], 'Number');
      }
      if (data.hasOwnProperty('homeMunicipalityCode')) {
        obj['homeMunicipalityCode'] = ApiClient.convertToType(data['homeMunicipalityCode'], 'String');
      }
      if (data.hasOwnProperty('homeMunicipalityName')) {
        obj['homeMunicipalityName'] = I18N.constructFromObject(data['homeMunicipalityName']);
      }
      if (data.hasOwnProperty('gender')) {
        obj['gender'] = Gender.constructFromObject(data['gender']);
      }
      if (data.hasOwnProperty('occupation')) {
        obj['occupation'] = ApiClient.convertToType(data['occupation'], 'String');
      }
      if (data.hasOwnProperty('language')) {
        obj['language'] = Language.constructFromObject(data['language']);
      }
      if (data.hasOwnProperty('firstName')) {
        obj['firstName'] = Name.constructFromObject(data['firstName']);
      }
      if (data.hasOwnProperty('finalPosition')) {
        obj['finalPosition'] = ApiClient.convertToType(data['finalPosition'], 'Number');
      }
      if (data.hasOwnProperty('position')) {
        obj['position'] = ApiClient.convertToType(data['position'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/Status} status
   */
  exports.prototype['status'] = undefined;
  /**
   * @member {module:model/CandidateMembership} membership
   */
  exports.prototype['membership'] = undefined;
  /**
   * @member {module:model/Name} lastName
   */
  exports.prototype['lastName'] = undefined;
  /**
   * @member {Number} age
   */
  exports.prototype['age'] = undefined;
  /**
   * @member {Number} comparativeIndex
   */
  exports.prototype['comparativeIndex'] = undefined;
  /**
   * @member {module:model/Votes} votes
   */
  exports.prototype['votes'] = undefined;
  /**
   * @member {Number} candidateNumber
   */
  exports.prototype['candidateNumber'] = undefined;
  /**
   * @member {String} homeMunicipalityCode
   */
  exports.prototype['homeMunicipalityCode'] = undefined;
  /**
   * @member {module:model/I18N} homeMunicipalityName
   */
  exports.prototype['homeMunicipalityName'] = undefined;
  /**
   * @member {module:model/Gender} gender
   */
  exports.prototype['gender'] = undefined;
  /**
   * @member {String} occupation
   */
  exports.prototype['occupation'] = undefined;
  /**
   * @member {module:model/Language} language
   */
  exports.prototype['language'] = undefined;
  /**
   * @member {module:model/Name} firstName
   */
  exports.prototype['firstName'] = undefined;
  /**
   * @member {Number} finalPosition
   */
  exports.prototype['finalPosition'] = undefined;
  /**
   * @member {Number} position
   */
  exports.prototype['position'] = undefined;



  return exports;
}));


