/**
 * Election
 * KSF Media's election service
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Election) {
      root.Election = {};
    }
    root.Election.CandidateMembership = factory(root.Election.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The CandidateMembership model module.
   * @module model/CandidateMembership
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>CandidateMembership</code>.
   * @alias module:model/CandidateMembership
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>CandidateMembership</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CandidateMembership} obj Optional instance to populate.
   * @return {module:model/CandidateMembership} The populated <code>CandidateMembership</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('MEMBER_OF_PARLIAMENT')) {
        obj['MEMBER_OF_PARLIAMENT'] = ApiClient.convertToType(data['MEMBER_OF_PARLIAMENT'], 'Boolean');
      }
      if (data.hasOwnProperty('MEMBER_OF_EUROPEAN_PARLIAMENT')) {
        obj['MEMBER_OF_EUROPEAN_PARLIAMENT'] = ApiClient.convertToType(data['MEMBER_OF_EUROPEAN_PARLIAMENT'], 'Boolean');
      }
      if (data.hasOwnProperty('MUNICIPAL_COUNCILOR')) {
        obj['MUNICIPAL_COUNCILOR'] = ApiClient.convertToType(data['MUNICIPAL_COUNCILOR'], 'Boolean');
      }
      if (data.hasOwnProperty('REGIONAL_COUNCILOR')) {
        obj['REGIONAL_COUNCILOR'] = ApiClient.convertToType(data['REGIONAL_COUNCILOR'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * @member {Boolean} MEMBER_OF_PARLIAMENT
   */
  exports.prototype['MEMBER_OF_PARLIAMENT'] = undefined;
  /**
   * @member {Boolean} MEMBER_OF_EUROPEAN_PARLIAMENT
   */
  exports.prototype['MEMBER_OF_EUROPEAN_PARLIAMENT'] = undefined;
  /**
   * @member {Boolean} MUNICIPAL_COUNCILOR
   */
  exports.prototype['MUNICIPAL_COUNCILOR'] = undefined;
  /**
   * @member {Boolean} REGIONAL_COUNCILOR
   */
  exports.prototype['REGIONAL_COUNCILOR'] = undefined;



  return exports;
}));


