/**
 * Election
 * KSF Media's articles service
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Election) {
      root.Election = {};
    }
    root.Election.I18N = factory(root.Election.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The I18N model module.
   * @module model/I18N
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>I18N</code>.
   * @alias module:model/I18N
   * @class
   * @param finnish {String} 
   */
  var exports = function(finnish) {
    var _this = this;

    _this['finnish'] = finnish;
  };

  /**
   * Constructs a <code>I18N</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/I18N} obj Optional instance to populate.
   * @return {module:model/I18N} The populated <code>I18N</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('finnish')) {
        obj['finnish'] = ApiClient.convertToType(data['finnish'], 'String');
      }
      if (data.hasOwnProperty('english')) {
        obj['english'] = ApiClient.convertToType(data['english'], 'String');
      }
      if (data.hasOwnProperty('swedish')) {
        obj['swedish'] = ApiClient.convertToType(data['swedish'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} finnish
   */
  exports.prototype['finnish'] = undefined;
  /**
   * @member {String} english
   */
  exports.prototype['english'] = undefined;
  /**
   * @member {String} swedish
   */
  exports.prototype['swedish'] = undefined;



  return exports;
}));


