/**
 * Election
 * KSF Media's election service
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Election) {
      root.Election = {};
    }
    root.Election.Language = factory(root.Election.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';


  /**
   * Enum class Language.
   * @enum {}
   * @readonly
   */
  var exports = {
    /**
     * value: "FI"
     * @const
     */
    "FI": "FI",
    /**
     * value: "SE"
     * @const
     */
    "SE": "SE",
    /**
     * value: "SV"
     * @const
     */
    "SV": "SV",
    /**
     * value: "EN"
     * @const
     */
    "EN": "EN"  };

  /**
   * Returns a <code>Language</code> enum value from a Javascript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
   * @return {module:model/Language} The enum <code>Language</code> value.
   */
  exports.constructFromObject = function(object) {
    return object;
  }

  return exports;
}));


