/**
 * Election
 * KSF Media's election service
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Election) {
      root.Election = {};
    }
    root.Election.Votes = factory(root.Election.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The Votes model module.
   * @module model/Votes
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Votes</code>.
   * @alias module:model/Votes
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>Votes</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Votes} obj Optional instance to populate.
   * @return {module:model/Votes} The populated <code>Votes</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('advanceVotes')) {
        obj['advanceVotes'] = ApiClient.convertToType(data['advanceVotes'], 'Number');
      }
      if (data.hasOwnProperty('advancePercent')) {
        obj['advancePercent'] = ApiClient.convertToType(data['advancePercent'], 'Number');
      }
      if (data.hasOwnProperty('electionDayPercent')) {
        obj['electionDayPercent'] = ApiClient.convertToType(data['electionDayPercent'], 'Number');
      }
      if (data.hasOwnProperty('electionDayVotes')) {
        obj['electionDayVotes'] = ApiClient.convertToType(data['electionDayVotes'], 'Number');
      }
      if (data.hasOwnProperty('totalPercent')) {
        obj['totalPercent'] = ApiClient.convertToType(data['totalPercent'], 'Number');
      }
      if (data.hasOwnProperty('totalVotes')) {
        obj['totalVotes'] = ApiClient.convertToType(data['totalVotes'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Number} advanceVotes
   */
  exports.prototype['advanceVotes'] = undefined;
  /**
   * @member {Number} advancePercent
   */
  exports.prototype['advancePercent'] = undefined;
  /**
   * @member {Number} electionDayPercent
   */
  exports.prototype['electionDayPercent'] = undefined;
  /**
   * @member {Number} electionDayVotes
   */
  exports.prototype['electionDayVotes'] = undefined;
  /**
   * @member {Number} totalPercent
   */
  exports.prototype['totalPercent'] = undefined;
  /**
   * @member {Number} totalVotes
   */
  exports.prototype['totalVotes'] = undefined;



  return exports;
}));


