/**
 * Election
 * KSF Media's articles service
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Election);
  }
}(this, function(expect, Election) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Election.CandidateMembership();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CandidateMembership', function() {
    it('should create an instance of CandidateMembership', function() {
      // uncomment below and update the code to test CandidateMembership
      //var instance = new Election.CandidateMembership();
      //expect(instance).to.be.a(Election.CandidateMembership);
    });

    it('should have the property MEMBER_OF_PARLIAMENT (base name: "MEMBER_OF_PARLIAMENT")', function() {
      // uncomment below and update the code to test the property MEMBER_OF_PARLIAMENT
      //var instance = new Election.CandidateMembership();
      //expect(instance).to.be();
    });

    it('should have the property MEMBER_OF_EUROPEAN_PARLIAMENT (base name: "MEMBER_OF_EUROPEAN_PARLIAMENT")', function() {
      // uncomment below and update the code to test the property MEMBER_OF_EUROPEAN_PARLIAMENT
      //var instance = new Election.CandidateMembership();
      //expect(instance).to.be();
    });

    it('should have the property MUNICIPAL_COUNCILOR (base name: "MUNICIPAL_COUNCILOR")', function() {
      // uncomment below and update the code to test the property MUNICIPAL_COUNCILOR
      //var instance = new Election.CandidateMembership();
      //expect(instance).to.be();
    });

    it('should have the property REGIONAL_COUNCILOR (base name: "REGIONAL_COUNCILOR")', function() {
      // uncomment below and update the code to test the property REGIONAL_COUNCILOR
      //var instance = new Election.CandidateMembership();
      //expect(instance).to.be();
    });

  });

}));
